### ISSUE TITLE
Low boot resolution

### ISSUE THREAD

**Issue by alirezatheh** [rubinda/hackintosh-n550#1]
I try to disable CSM to get a higher resolution. This works but the login screen is totally disturbed, so in general I have to enable CSM to make it work. Any idea?

**Comment by rubinda** [comment]
Hi there!
I have CSM currently enabled, if i recall correctly turning it off did make my login screen go fuzzy. I am still using these exact files for my N550-JV.

In case of graphics issues, you might want to look into disabling the dedicated GPU (I didn't even bother to try using it)
 [using a hot patch](https://github.com/rubinda/hackintosh-n550/blob/main/EFI/OC/ACPI/SSDT-dGPU-Off.aml), perhaps WEG (WhateverGreen) would work (there was some flag to disable dgpu, but I don't remember exactly)

I also had to use some patch (framebuffer-cursormem 00009000) to fix minor graphics glitches (some horizontal lines and weird behavior during web browsing occurred otherwise), the latter was described here -> [Dortania Guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#add-2)

The [Dortania guide](https://dortania.github.io/OpenCore-Install-Guide/config.plist/haswell.html#starting-point) was a lifesaver while trying to make things work.

Can you login with CSM enabled? Are you sure your graphics are properly detected? You could try using different AAPL,ig-platform-id, but keep in mind, that I also had to set a fake device-id for my 4600. Some values I used for testing are available [here](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md)

I can't promise to make it work, but let me know if you need more help :)

**Comment by alirezatheh** [comment]
Yes with CSM enabled everything is fine except boot resolution. I already have those setting you mentioned.

**Comment by rubinda** [comment]
Ohh, you mean during boot selection? I also have a lower resolution there, never really bothered me. It changes sometime during the Apple loading icon around halfway. Since the OS then has a normal resolution I never spent much time on it.

The only fix I've found for that was to disable CSM, but as you already mentioned that breaks macOS on these laptops.

Btw, does sleep work for you? Any luck with keyboard brightness?

**Comment by alirezatheh** [comment]
Yes I used your ATK patches and keyboard brightness is working. It's weird that you can't get it working. Sleep is also fine. Sleep problems usually refers to wrong USB mapping (also all devices should be unplugged such as mouse). [Here](https://github.com/rubinda/hackintosh-n550/files/6005895/Archive.zip) is my config.plist and USBPorts.kext. Need to mention that My N550JK has screen touch. So if yours has not, you should delete the HS10 port.

**Comment by alirezatheh** [comment]
Update: I managed to fix boot resolution by modding my BIOS. Just replaced CsmVideo with HermitCsmVideo and everything is great now.

**Comment by rubinda** [comment]
Thank you!
Sorry I was a bit busy the last few days. I am glad that you resolved the issue and I will definitely look into your suggestions.

Happy hackintoshing!
